## Exercice 1

In [19]:
# 1- Demander les dimensions de A et B

dim_A_lin=int(input("Donner le nombre de lignes de la matrice A : "))
dim_A_col=int(input("Donner le nombre de colones de la matrice A : "))
dim_B_lin=int(input("Donner le nombre de lignes de la matrice B : "))
dim_B_col=int(input("Donner le nombre de colones de la matrice B : "))

Donner le nombre de lignes de la matrice A : 3
Donner le nombre de colones de la matrice A : 3
Donner le nombre de lignes de la matrice B : 3
Donner le nombre de colones de la matrice B : 3


In [20]:
# 2- Creer une matrice identité A - tester si la matrice est carré

import numpy as np
if dim_A_lin == dim_A_col:
    A_ident=np.eye(dim_A_lin)
    print(A_ident)
else:
    print("Pas possible de creer une matrice identité non carré. \nLe nombre de lignes doit être égal au nombre de colones")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# 3 - Creer une matrice aléatoire B

B=np.random.randint(10, size=((dim_B_lin),(dim_B_col)))
print(B)

[[2 2 2]
 [7 8 7]
 [9 3 3]]


In [22]:
# 4 - Sommer les deux matrices A_ident et B

if (dim_A_lin==dim_B_lin) and (dim_A_col==dim_B_col):
    C=[]
    for i in range(dim_A_lin):
        sm=[]
        for j in range(dim_A_col):
            elemento=A_ident[i][j]+B[i][j] 
            sm.append(elemento)
        C.append(sm)
    print("C=",C)
else:
    print("Pas possible sommer des matrices de formats differents.")
    

C= [[3.0, 2.0, 2.0], [7.0, 9.0, 7.0], [9.0, 3.0, 4.0]]


## Exercice 2

In [23]:
# Definir la matrice A1 et afficher les éléments de la matrice A1

A1 = [[2,5,-3,-2],[-2,-3,2,-5],[1,3,-2,2],[-1,-6,4,3]]
print(A1)

[[2, 5, -3, -2], [-2, -3, 2, -5], [1, 3, -2, 2], [-1, -6, 4, 3]]


In [24]:
# Remplacer les éléments négatifs de A1 para zéros et afficher la nouveau matrice

for i in range(len(A1)):
    for j in range(len(A1[0])):
        if A1[i][j] < 0:
            A1[i][j]=0
print(A1)

[[2, 5, 0, 0], [0, 0, 2, 0], [1, 3, 0, 2], [0, 0, 4, 3]]
